export default [
  {
    id: '1',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x140',
    price: 235,
    promotionalPrice: 215,
  },
  {
    id: '2',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x141',
    price: 235,
    promotionalPrice: 215,
  },
  {
    id: '3',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x142',
    price: 235,
    promotionalPrice: 215,
  },
  {
    id: '4',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x143',
    price: 235,
    promotionalPrice: 215,
  },
  {
    id: '5',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x144',
    price: 235,
    promotionalPrice: 215,
  },
  {
    id: '6',
    name: 'Camisa',
    slug: 'camisa-0',
    image: 'https://source.unsplash.com/user/willianjusten/300x145',
    price: 235,
    promotionalPrice: 215,
  },
];
